# jekyll serve
host: 0.0.0.0

# Build settings
theme: simplicity
plugins:
  - jekyll-feed
  - jekyll-paginate

# Theme settings
paginate: 10
disqus_username: bananaappletw
twitter: https://twitter.com/bananaappletw
github: https://github.com/bananaappletw
stack_overflow: https://stackoverflow.com/users/4446356/bananaappletw
facebook: https://www.facebook.com/bananaappletw
linkedin: https://www.linkedin.com/in/bananaappletw/
