# Blog config

title: bananaappletw
url: bananaappletw.github.io
date_format: "%b %-d, %Y"
host: 0.0.0.0

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-assets
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate-v2
  - font-awesome-sass
  - bulma-sass
  - octopress-escape-code

# octopress-escape-code

escape_code: true

# Jekyll-assets

assets:
  caching:
    type: memory

# Jekyll-paginate-v2

pagination:
  per_page: 5
  permalink: '/:num/'
  enabled: true
  debug: true
  sort_field: 'date'
  sort_reverse: true

# Jekyll-tagging

tag_page_layout: tags
tag_page_dir: tags

# Theme settings

twitter: https://twitter.com/bananaappletw
github: https://github.com/bananaappletw
stack_overflow: https://stackoverflow.com/users/4446356/bananaappletw
facebook: https://www.facebook.com/bananaappletw
linkedin: https://www.linkedin.com/in/bananaappletw/
disqus:
  shortname: bananaappletw
google_analytics: UA-105275050-1
encoding: utf-8
