# Blog config
url: bananaappletw.github.io
date_format: "%b %-d, %Y"

# jekyll serve

host: 0.0.0.0

# Build settings

plugins:
  - jekyll-assets
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - font-awesome-sass
  - bulma-sass

# Jekyll-assets

assets:
  caching:
    type: memory

# Jekyll-paginate-v2

pagination:
  per_page: 5
  permalink: '/:num/'
  enabled: true
  debug: true
  sort_field: 'date'
  sort_reverse: true

# Jekyll-tagging

tag_page_layout: tags
tag_page_dir: tags

# Theme settings

twitter: https://twitter.com/bananaappletw
github: https://github.com/bananaappletw
stack_overflow: https://stackoverflow.com/users/4446356/bananaappletw
facebook: https://www.facebook.com/bananaappletw
linkedin: https://www.linkedin.com/in/bananaappletw/
disqus:
  shortname: bananaappletw
google_analytics: UA-105275050-1
encoding: utf-8
